language: node_js
node_js:
 - "node"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage:  test
      script: npm test
    - stage:  deploy
      if:     branch = master
      script: npm run deploy -- --token "$FIREBASE_TOKEN"
