language: node_js
node_js:
 - "node"
cache: yarn

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy
      if: branch = master
      script: yarn deploy --token "$FIREBASE_TOKEN"
